services:
  - type: web
    name: ai-builder-api
    env: node
    plan: free
    region: oregon
    rootDir: server       # ↖ 반드시 server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        fromEnvironment: OPENAI_API_KEY
      - key: MONGODB_URI
        fromEnvironment: MONGODB_URI